#!/usr/bin/env python3
"""
test_workflow.py — Full workflow test for TRAE OpenClaw MCP Integration

Demonstrates the complete cycle:
  1. Connect to MCP socket
  2. Ping the server
  3. List available tools
  4. Get workspace info
  5. List workspace root
  6. Create a test file
  7. Search for content in the file
  8. Read the file back
  9. Clean up

Usage:
    python3 test_workflow.py
    TRAE_MCP_SOCK=/tmp/trae-openclaw-mcp.sock python3 test_workflow.py
"""

import sys
import json
import time
import os

# Add parent directory so we can import mcp_client
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from mcp_client import connect, send_rpc, call_tool, C, ok, error, warn, info, section, pretty_json

SOCKET_PATH = os.environ.get("TRAE_MCP_SOCK", "/tmp/trae-openclaw-mcp.sock")
TEST_FILE_PATH = "openclaw-test-output.txt"
TEST_CONTENT = """\
# OpenClaw MCP Test File
# Generated by test_workflow.py

Hello from OpenClaw! This file was created via the TRAE MCP integration.

The quick brown fox jumps over the lazy dog.
SEARCH_MARKER: found_it_42
"""

PASS = 0
FAIL = 0

def run_step(label: str, fn):
    """Run a test step. Returns the result or None on failure."""
    global PASS, FAIL
    print(f"\n{C.BOLD}[TEST]{C.RESET} {label}")
    try:
        result = fn()
        ok(f"PASS: {label}")
        PASS += 1
        return result
    except Exception as e:
        error(f"FAIL: {label}")
        error(f"  → {e}")
        FAIL += 1
        return None


def main():
    section("TRAE MCP Full Workflow Test")
    info(f"Socket: {SOCKET_PATH}")
    print()

    # ── Step 1: Connect ──────────────────────────────────────────────────────
    sock = run_step("Connect to MCP socket", lambda: connect(SOCKET_PATH, retries=3))
    if sock is None:
        error("Cannot proceed without a connection. Is TRAE running?")
        error("Start it: Ctrl+Shift+P → 'TRAE MCP: Start Server'")
        sys.exit(1)

    workspace_root = None

    try:
        # ── Step 2: Ping ─────────────────────────────────────────────────────
        def step_ping():
            resp = send_rpc(sock, "ping")
            assert resp.get("result", {}).get("status") == "ok", f"Unexpected ping response: {resp}"
            tools_listed = resp["result"].get("tools", [])
            info(f"  Server tools: {', '.join(tools_listed)}")
            return resp

        run_step("Ping server", step_ping)

        # ── Step 3: List tools ───────────────────────────────────────────────
        def step_list_tools():
            resp = send_rpc(sock, "tools/list")
            tools = resp.get("result", {}).get("tools", [])
            assert len(tools) > 0, "No tools returned"
            for t in tools:
                print(f"    {C.CYAN}• {t['name']}{C.RESET}")
            return [t["name"] for t in tools]

        tools_available = run_step("List available tools", step_list_tools) or []

        # ── Step 4: Get workspace ────────────────────────────────────────────
        def step_get_workspace():
            result = call_tool(sock, "get_workspace", {})
            root = result.get("root")
            folders = result.get("folders", [])
            info(f"  Workspace root: {root}")
            info(f"  Folders: {[f['name'] for f in folders]}")
            assert root is not None, "No workspace root returned"
            return root

        workspace_root = run_step("Get workspace info", step_get_workspace)

        # ── Step 5: List workspace root ───────────────────────────────────────
        def step_list_dir():
            result = call_tool(sock, "list_dir", {})
            entries = result.get("entries", [])
            info(f"  Found {len(entries)} entries in workspace root")
            for e in entries[:10]:
                icon = "📁" if e["isDirectory"] else "📄"
                print(f"    {icon} {e['name']}")
            if len(entries) > 10:
                info(f"  ... and {len(entries) - 10} more")
            return entries

        run_step("List workspace root directory", step_list_dir)

        # ── Step 6: Write test file ───────────────────────────────────────────
        def step_write_file():
            result = call_tool(sock, "write_file", {
                "path": TEST_FILE_PATH,
                "content": TEST_CONTENT
            })
            assert result.get("written") is True, f"Write failed: {result}"
            info(f"  Written {result.get('size', '?')} bytes to {result.get('path', TEST_FILE_PATH)}")
            return result

        run_step(f"Write test file: {TEST_FILE_PATH}", step_write_file)

        # ── Step 7: Search codebase ───────────────────────────────────────────
        def step_search():
            result = call_tool(sock, "search_codebase", {
                "query": "SEARCH_MARKER",
                "pattern": "*.txt"
            })
            count = result.get("count", 0)
            results = result.get("results", [])
            info(f"  Found {count} match(es) for 'SEARCH_MARKER'")
            for r in results:
                print(f"    {C.GREEN}{r.get('file', '?')}:{r.get('line', '?')}{C.RESET}  {r.get('text', '').strip()}")
            assert count > 0, "Search returned 0 results — expected at least 1"
            return results

        run_step("Search for 'SEARCH_MARKER' in *.txt files", step_search)

        # ── Step 8: Read file back ────────────────────────────────────────────
        def step_read_file():
            result = call_tool(sock, "read_file", {"path": TEST_FILE_PATH})
            content = result.get("content", "")
            assert "Hello from" in content, "Expected 'Hello from' in file content"
            assert "SEARCH_MARKER" in content, "Expected 'SEARCH_MARKER' in file content"
            info(f"  Read {result.get('size', '?')} bytes")
            info(f"  First line: {content.splitlines()[0]}")
            return content

        run_step(f"Read {TEST_FILE_PATH} back", step_read_file)

        # ── Step 9: Run a command ─────────────────────────────────────────────
        def step_run_command():
            result = call_tool(sock, "run_command", {"command": "echo 'agent says hello'"})
            stdout = result.get("stdout", "").strip()
            assert "agent says hello" in stdout, f"Unexpected output: {stdout}"
            info(f"  Output: {stdout}")
            return result

        run_step("Run shell command: echo", step_run_command)

        # ── Step 10: Get open editors (new tool) ──────────────────────────────
        if "get_open_editors" in tools_available:
            def step_get_editors():
                result = call_tool(sock, "get_open_editors", {})
                editors = result.get("editors", [])
                info(f"  Open editors: {len(editors)}")
                for ed in editors:
                    print(f"    {C.CYAN}• {ed.get('path', ed.get('name', '?'))}{C.RESET}")
                return result

            run_step("Get open editors", step_get_editors)
        else:
            warn("Skipping get_open_editors (tool not registered yet)")

    finally:
        sock.close()

    # ── Summary ───────────────────────────────────────────────────────────────
    section("Test Summary")
    total = PASS + FAIL
    print(f"\n  {C.GREEN}Passed: {PASS}/{total}{C.RESET}   {C.RED}Failed: {FAIL}/{total}{C.RESET}\n")

    if FAIL == 0:
        ok("All tests passed! 🎉")
    else:
        warn(f"{FAIL} test(s) failed. Check TRAE is running and the extension is active.")
        sys.exit(1)


if __name__ == "__main__":
    main()
